package edu.washington.escience.myria.operator.network;

import java.util.List;

import edu.washington.escience.myria.operator.Operator;
import edu.washington.escience.myria.operator.network.partition.BroadcastPartitionFunction;
import edu.washington.escience.myria.parallel.ExchangePairID;
import edu.washington.escience.myria.parallel.ipc.IPCConnectionPool;

/**
 * The producer part of the Collect Exchange operator.
 * 
 * The producer actively pushes the tuples generated by the child operator to the paired LocalMultiwayConsumer.
 * 
 */
public final class LocalMultiwayProducer extends GenericShuffleProducer {

  /** Required for Java serialization. */
  private static final long serialVersionUID = 1L;

  /**
   * @param child the child who provides data for this producer to distribute.
   * @param operatorIDs destination operators the data goes
   */
  public LocalMultiwayProducer(final Operator child, final List<ExchangePairID> operatorIDs) {
    super(child, operatorIDs, IPCConnectionPool.SELF_IPC_ID, new BroadcastPartitionFunction());
  }

}
